=== DmitriyWolverine/HTP_JD1_XML_PARSERS/src/resources/xml/library_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- officical_namespace -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.htp.by/library_schema" 
		xmlns:library="http://www.htp.by/library_schema" 
		elementFormDefault="qualified">
		
		<xs:element name="library" type="library:library_type"/>
		
		<xs:complexType name="library_type">
			<xs:sequence>
				<xs:element name="books" type="library:books_type"/>
				<xs:element name="employees" type="library:employees_type"/>
			</xs:sequence>
			<xs:attribute name="start-date" type="xs:date"></xs:attribute>
		</xs:complexType>
		
		<xs:complexType name="books_type" >
				<xs:sequence>
					<xs:element name="book" type="library:one_book_type" maxOccurs="unbounded"></xs:element>
				</xs:sequence>
		</xs:complexType>
		
		<xs:complexType name="employees_type" >
				<xs:sequence>
            <xs:element name="employee" type="library:one_employee_type" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
		</xs:complexType>
		
		<xs:complexType name="one_book_type" >
			<xs:sequence>
				<xs:element name="id" type="xs:int"></xs:element>
				<xs:element name="title" type="xs:string"></xs:element>
				<xs:element name="author" type="xs:string"></xs:element>
				<xs:element name="publishedYear" type="xs:int"></xs:element>
			</xs:sequence>
		</xs:complexType>		
		
		<xs:complexType name="one_employee_type" >
			<xs:sequence>
				<xs:element name="id" type="xs:int"></xs:element>
				<xs:element name="name" type="xs:string"></xs:element>
				<xs:element name="surname" type="xs:string"></xs:element>
				<xs:element name="birthday" type="xs:date"></xs:element>
				<xs:element name="email" type="xs:string"></xs:element>
				<xs:element name="readBookId" type="xs:int" maxOccurs="unbounded"></xs:element>
			</xs:sequence>
		</xs:complexType>		
		
</xs:schema>

=== DmitriyWolverine/HTP_JD1_XML_PARSERS/src/resources/xml/library.xml
<?xml version="1.0" encoding="UTF-8"?>

<library start-date="2018-02-10"
xmlns="http://www.htp.by/library_schema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.htp.by/library_schema library_schema.xsd">

	<books>
		<book>
			<id>1</id>
			<title>War and peace</title>
			<author>Tolstoy</author>
			<publishedYear>1843</publishedYear>
		</book>
		
		<book>
			<id>2</id>
			<title>Anna Karenina</title>
			<author>Tolstoy</author>
			<publishedYear>1875</publishedYear>
		</book>
		
		<book>
			<id>3</id>
			<title>MuMy</title>
			<author>Turgenev</author>
			<publishedYear>1798</publishedYear>
		</book>
		<book>
			<id>4</id>
			<title>Master an margaret</title>
			<author>Bulgakov</author>
			<publishedYear>1927</publishedYear>
		</book>
		
		<book>
			<id>5</id>
			<title>Evgeniy Onegin</title>
			<author>Pushkin</author>
			<publishedYear>1806</publishedYear>
		</book>
		
	</books>
	
	<employees>
		<employee>
			<id>1</id>
			<name>Dima</name>
			<surname>Shabunevich</surname>
			<birthday>1993-05-18</birthday>
			<email>shab@gmail.com</email>
			<readBookId>1</readBookId>
			<readBookId>2</readBookId>
			<readBookId>4</readBookId>
		</employee>
		
		<employee>
			<id>2</id>
			<name>Anna</name>
			<surname>Petrova</surname>
			<birthday>1992-11-03</birthday>
			<email>annaP@gmail.com</email>
			<readBookId>1</readBookId>
			<readBookId>3</readBookId>
		</employee>
		
		<employee>
			<id>3</id>
			<name>Irina</name>
			<surname>Stepanova</surname>
			<birthday>1995-06-22</birthday>
			<email>Stepanova@gmail.com</email>
			<readBookId>1</readBookId>
			<readBookId>2</readBookId>
			<readBookId>3</readBookId>
			<readBookId>4</readBookId>
			<readBookId>5</readBookId>
		</employee>
		
		<employee>
			<id>4</id>
			<name>Misha</name>
			<surname>Ergulovich</surname>
			<birthday>1992-03-05</birthday>
			<email>v@gmail.com</email>
			<readBookId>5</readBookId>
		</employee>
	</employees>

</library>
